/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-7.0
 * 
 * Declare the vtkProjectedAAHexahedraMapper_FS string.
 *
 */
#ifndef __vtkProjectedAAHexahedraMapper_FS_h
#define __vtkProjectedAAHexahedraMapper_FS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkProjectedAAHexahedraMapper_FS;

#endif /* #ifndef __vtkProjectedAAHexahedraMapper_FS_h */
